name: Build susfs jni
on:
  workflow_dispatch:

jobs:
  build:
    name: Build userspace susfs jni
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d
    - name: Build susfs jni
      working-directory: ./userspace/susfs
      run: ndk-build
    - name: Upload susfs jni
      uses: actions/upload-artifact@v4
      with:
        name: ksu_susfs
        path: ./userspace/susfs/libs
    - name: Create module
      run: |
        cp ./userspace/susfs/libs/arm64-v8a/ksu_susfs ./module/tools/ksu_susfs_arm64
        cp ./userspace/susfs/libs/armeabi-v7a/ksu_susfs ./module/tools/ksu_susfs_arm
    - name: Upload module
      uses: actions/upload-artifact@v4
      with:
        name: susfs_userspace_module.zip
        path: ./module/*
